# Generated by Django 5.2.7 on 2025-10-15 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Voucer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discount_percentage', models.IntegerField()),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
