# Generated by Django 5.2.7 on 2025-10-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voucer',
            new_name='Voucher',
        ),
    ]
