# Generated by Django 5.2.7 on 2025-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_address_cart_cart_dish_invoice_order_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
