# Generated by Django 5.2.7 on 2025-11-03 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_dish_course_alter_dish_descrizione_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.dish', verbose_name='Piatto preferito'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='vote',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(49)], verbose_name='Punteggio'),
        ),
    ]
