# Generated by Django 5.2.7 on 2025-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_rating_dish_alter_rating_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='feedback',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
