# Generated by Django 5.2.7 on 2025-10-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dish_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.course'),
        ),
    ]
