# Generated by Django 5.2.7 on 2025-10-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_dish_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.course', verbose_name='Portata'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Senza glutine'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prezzo'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegano'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetariano'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gluten_free',
            field=models.BooleanField(default=False, verbose_name='Senza glutine'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegano'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetariano'),
        ),
    ]
