# Generated by Django 5.2.7 on 2025-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_dish_course_alter_dish_descrizione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Prezzo'),
        ),
    ]
